name: rfpy_teste
channels:
  - intel
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - intelpython=2021.1.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libstdcxx-ng=9.3.0
  - openssl=1.1.1j
  - pip=21.0.1
  - python=3.7.9
  - setuptools=51.1.2
  - sqlite=3.34.0
  - tcl=8.6.10
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11.1
  - pip:
    - colorama==0.4.4
    - commonmark==0.9.1
    - cython==0.29.23
    - et-xmlfile==1.1.0
    - fastcore==1.3.20
    - feather-format==0.4.1
    - numpy==1.20.3
    - openpyxl==3.0.7
    - packaging==20.9
    - pandas==1.2.4
    - pyarrow==4.0.0
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pytz==2021.1
    - rich==10.2.0
    - typing-extensions==3.10.0.0
