name: rfpy
channels:
  - intel
  - defaults
dependencies:
  - bzip2=1.0.8
  - certifi=2020.12.5
  - intelpython=2021.1.1
  - libpython=2.1
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - msys2-conda-epoch=20160418
  - openssl=1.1.1d
  - pip=21.0.1
  - python=3.7.7
  - setuptools=51.1.2
  - sqlite=3.30.1
  - tcl=8.6.9
  - tk=8.6.9
  - vc=14.0
  - vs2015_runtime=14.16.27012
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.4
  - zlib=1.2.11.1
  - pip:
    - colorama==0.4.4
    - commonmark==0.9.1
    - cython==0.29.23
    - et-xmlfile==1.1.0
    - fastcore==1.3.20
    - feather-format==0.4.1
    - numpy==1.20.3
    - openpyxl==3.0.7
    - packaging==20.9
    - pandas==1.2.4
    - pyarrow==4.0.0
    - pygments==2.9.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - rich==10.2.0
    - six==1.16.0
    - typing-extensions==3.10.0.0