name: rfpy
channels:
  - conda-forge
  - intel
  - defaults
dependencies:
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - intelpython=2021.1.1
  - libpython=2.1
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - msys2-conda-epoch=20160418
  - openssl=1.1.1k
  - pip=21.1.2
  - python=3.7.10
  - python_abi=3.7
  - setuptools=52.0.0
  - sqlite=3.35.5
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wheel=0.36.2
  - wincertstore=0.2
  - pip:
    - argon2-cffi==20.1.0
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cffi==1.14.5
    - colorama==0.4.4
    - commonmark==0.9.1
    - cython==0.29.23
    - decorator==5.0.9
    - defusedxml==0.7.1
    - entrypoints==0.3
    - et-xmlfile==1.1.0
    - fastcore==1.3.20
    - fastrelease==0.1.11
    - feather-format==0.4.1
    - ghapi==0.1.17
    - importlib-metadata==4.4.0
    - ipykernel==5.5.5
    - ipython==7.24.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-widgets==1.0.0
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbdev==1.1.14
    - nbformat==5.1.3
    - notebook==6.4.0
    - numpy==1.20.3
    - openpyxl==3.0.7
    - packaging==20.9
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pickleshare==0.7.5
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.18
    - pyarrow==4.0.1
    - pycparser==2.20
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pywin32==301
    - pywinpty==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.1.0
    - qtconsole==5.1.0
    - qtpy==1.9.0
    - rich==10.2.2
    - send2trash==1.5.0
    - six==1.16.0
    - terminado==0.10.0
    - testpath==0.5.0
    - tornado==6.1
    - traitlets==5.0.5
    - typing-extensions==3.10.0.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.4.1
