package:
  name: rfpye
  version: 0.2.0
source:
  sha256: a7d80f305739e28e7a6255628e4708243a51d6e92a6624240211ee6a809dcc44
  url: https://files.pythonhosted.org/packages/c8/4f/9176ec58d57b5d057191b48a6e1c491e19708d880baa7b29947772de58c4/rfpye-0.2.0.tar.gz
about:
  dev_url: https://ronaldokun.github.io
  doc_url: https://ronaldokun.github.io
  home: https://ronaldokun.github.io
  license: Apache Software
  license_family: APACHE
  summary: Binary Files Parser resulted from the script Logger from CRFS - Rfeye Node
    Equipament
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - ronaldokun
requirements:
  host:
  - pip
  - python
  - packaging
  - Cython
  - numpy
  - fastcore
  - feather-format
  - pandas
  - rich
  - openpyxl
  - loguru
  run:
  - pip
  - python
  - packaging
  - Cython
  - numpy
  - fastcore
  - feather-format
  - pandas
  - rich
  - openpyxl
  - loguru
test:
  imports:
  - rfpye
